version: "3"
services:
  video-streaming:
    image: video-streaming # The image to build
    build: # Options used when building the image
      context: ./video-streaming # Root dir for the microservice
      dockerfile: Dockerfile # Dockerfile name relative to the context
    container_name: video-streaming # Set the container's name

    ports:
      - "4000:80" # Map host port 4000 to container port 80

    environment:
      - PORT=80 # Set the PORT env var

    restart: "no" # Don't automatically restart when the service crashes
