version: "3"
services:
  video-streaming:
    image: video-streaming # The image to build
    build: # Options used when building the image
      context: ./video-streaming # Root dir for the microservice
      dockerfile: Dockerfile-dev # Dockerfile name relative to the context
    container_name: video-streaming # Set the container's name

    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z

    ports:
      - 4000:80 # Map host port 4000 to container port 80

    environment:
      - PORT=80 # Set the PORT env var
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://database:27017
      - DBNAME=video-streaming

    restart: "no" # Don't automatically restart when the service crashes

  google-storage:
    image: google-storage
    build:
      context: ./google-storage
    container_name: video-storage

    ports:
      - 4001:80

    environment:
      - PORT=80
      - GOOGLE_CREDENTIALS_EMAIL=email
      - GOOGLE_CREDENTIALS_PRIVATE_KEY=key
      - GOOGLE_PROJECT_ID=id

    restart: "no"

  database:
    image: mongo:4.2.8
    container_name: database

    ports:
      - 4002:27017

    restart: "always"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history

    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z

    ports:
      - 4003:80

    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://database:27017
      - DBNAME=history
      - RABBIT=amqp://guest:guest@rabbit:5672

    depends_on:
      - database
      - rabbit

    restart: "no"

  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit

    ports:
      - 5672:5672
      - 15672:15672

    expose:
      - 5672
      - 15672

    restart: always
